### ISSUE TITLE
debugger issue toString

### ISSUE THREAD

**Issue by F3der1co** [armandoalonso/fsm#1]
[FSMdebug.zip](https://github.com/armandoalonso/fsm/files/12467875/FSMdebug.zip)
steps to reproduce:
1. drag zip into c3
2. preview 
3. open the debugger and select the instance in it

observed:
keeps logging this error and creates infinite behavior instances
![image](https://github.com/armandoalonso/fsm/assets/89512047/fc740e7f-0098-484b-a236-0992280d98a2)

**Comment by armandoalonso** [comment]
ohh ill look into this asap

**Comment by armandoalonso** [comment]
Ahh I found the issue, when one of the properties is null (which in this case the previous State internal state was null, the debugger throws these exceptions, I will have a fix out for this shortly

**Comment by armandoalonso** [comment]
fixed in v1.0.0.2

![image](https://github.com/armandoalonso/fsm/assets/7579560/1cab6eed-a4b7-4b8e-8b13-6babaf03a259)
