### ISSUE TITLE
[Enhancement] compare current state to list of states

### ISSUE THREAD

**Issue by F3der1co** [armandoalonso/fsm#4]
When I am using a FSM I often have the same logic that should run when the FSM is one of  many states.
This can currently be solve like this:
![image](https://github.com/armandoalonso/fsm/assets/89512047/36c2fdbe-192a-48e7-8b6d-a93abdcf7d3d)
with an or block, the downside of this is that the conditions can get very long and more importantly it's fairly heavy as the event system loops over the picked instances once per condition.
To fix that I sometimes use a conditional operator like this:
![image](https://github.com/armandoalonso/fsm/assets/89512047/3e18224c-2ed4-4133-b7bf-a9da42e611b0)
this solves the performance overhead, but becomes hard to read because of the repeated "player.FSM.CurrentState ="

So my suggested solution would be an alternative condition where we can put in a list of states, it could look something like this:
![image](https://github.com/armandoalonso/fsm/assets/89512047/7b5c57ea-4d34-4adf-9c52-8ad466a34b15)
so it allows for a variable number of arguments separated by commas, if possible.

I guess one might argue you are not supposed to use a state machine like this, maybe? But to me this seems like a sensible thing to do.

**Comment by armandoalonso** [comment]
v1.0.0.3 should have 4 new conditions

Current State in List
Previous State in List
On State Enter in List
On State Exit in List

they each take comma separated list (string) of states, each element is trimmed so white spaces don't really matter but it is case-sensitive. 

code is simple for the conditions:

`     states = states.split(",").map((x) => x.trim());
      return this.enabled && states.includes(this.currentState);
`

**Comment by F3der1co** [comment]
amazing tysm!
